/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Admin': RouteRecordInfo<'/Admin', '/Admin', Record<never, never>, Record<never, never>>,
    '/Avaliacao': RouteRecordInfo<'/Avaliacao', '/Avaliacao', Record<never, never>, Record<never, never>>,
    '/Busca': RouteRecordInfo<'/Busca', '/Busca', Record<never, never>, Record<never, never>>,
    '/Musicas': RouteRecordInfo<'/Musicas', '/Musicas', Record<never, never>, Record<never, never>>,
    '/Perfil': RouteRecordInfo<'/Perfil', '/Perfil', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/Admin.vue': {
      routes: '/Admin'
      views: never
    }
    'src/pages/Avaliacao.vue': {
      routes: '/Avaliacao'
      views: never
    }
    'src/pages/Busca.vue': {
      routes: '/Busca'
      views: never
    }
    'src/pages/Musicas.vue': {
      routes: '/Musicas'
      views: never
    }
    'src/pages/Perfil.vue': {
      routes: '/Perfil'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
